#!/bin/bash

# It makes XML font metric for TTF font you provide. Be careful for correct JAR libs paths and check those before You use it.
# Using: ttf2fontmetric YourFont.ttf YourFont.xml

java -cp /srvs/fop-jetty/fop/build/fop.jar:/srvs/fop-jetty/fop/lib/serializer-2.7.0.jar:/srvs/fop-jetty/fop/lib/avalon-framework-4.2.0.jar:/srvs/fop-jetty/fop/lib/commons-logging-1.0.4.jar:/srvs/fop-jetty/fop/lib/commons-io-1.3.1.jar:/srvs/fop-jetty/fop/lib/xmlgraphics-commons-1.3.1.jar:/srvs/fop-jetty/fop/lib/xml-apis-1.3.04.jar:/srvs/fop-jetty/fop/lib/xercesImpl-2.7.1.jar:/srvs/fop-jetty/fop/lib/xalan-2.7.0.jar org.apache.fop.fonts.apps.TTFReader $1 $2
